[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afire = { version = "3.0.0-alpha.2", features = ["extensions", "tracing"] }
anyhow = "1.0.79"
dotenvy = "0.15.7"
